In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
dataset = pd.read_csv('C:\\Users\\fcbba\\Desktop\\CSV\logistic.csv')

In [20]:
X = dataset.iloc[:, [1, 2]].values
y = dataset.iloc[:, 3].values


In [21]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000]], dtype=int64)

In [22]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
      dtype=int64)

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [24]:
dataset

USER ID  AGE  INCOME  OWN HOUSE
0    252465   19   19000          0
1    252466   35   20000          0
2    252467   26   43000          0
3    252468   27   57000          0
4    252460   19   76000          0
5    252470   27   58000          0
6    252471   27   84000          0
7    252472   32  150000          1
8    252473   25   33000          0
9    252474   35   65000          0
10   252475   26   80000          0
11   252476   26   52000          0
12   252477   20   86000          0
13   252478   32   18000          0
14   252479   18   82000          0
15   252480   29   80000          0
16   252481   47   25000          1
17   252482   45   26000          1
18   252483   46   28000          1
19   252484   48   29000          1

In [25]:
X_train, X_test, y_train, y_test

(array([[    45,  26000],
        [    27,  84000],
        [    32,  18000],
        [    19,  76000],
        [    26,  43000],
        [    27,  58000],
        [    18,  82000],
        [    35,  65000],
        [    32, 150000],
        [    47,  25000],
        [    26,  52000],
        [    27,  57000],
        [    19,  19000],
        [    29,  80000],
        [    20,  86000]], dtype=int64),
 array([[   46, 28000],
        [   35, 20000],
        [   48, 29000],
        [   25, 33000],
        [   26, 80000]], dtype=int64),
 array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([1, 0, 1, 0, 0], dtype=int64))

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [28]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred

array([1, 0, 1, 0, 0], dtype=int64)

In [30]:
# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [31]:
cm

array([[3, 0],
       [0, 2]], dtype=int64)